ALTER TABLE `USER` ADD FOREIGN KEY (`id`) REFERENCES `STUDENT` (`id`);

ALTER TABLE `USER` ADD FOREIGN KEY (`id`) REFERENCES `LECTURER` (`id`);

ALTER TABLE `USER_PHONE_NO` ADD FOREIGN KEY (`user_id`) REFERENCES `USER` (`id`);

ALTER TABLE `LECTURER_DEGREE` ADD FOREIGN KEY (`lecturer_id`) REFERENCES `LECTURER` (`id`);

ALTER TABLE `STUDENT` ADD FOREIGN KEY (`dept_id`) REFERENCES `DEPARTMENT` (`id`);

ALTER TABLE `SUBJECT` ADD FOREIGN KEY (`dept_id`) REFERENCES `DEPARTMENT` (`id`);

ALTER TABLE `COURSE` ADD FOREIGN KEY (`sub_id`) REFERENCES `SUBJECT` (`id`);

ALTER TABLE `LECTURER` ADD FOREIGN KEY (`id`) REFERENCES `DEPARTMENT` (`chairman_id`);

ALTER TABLE `CHAIRMAN_TERM` ADD FOREIGN KEY (`dept_id`, `lecturer_id`) REFERENCES `DEPARTMENT` (`id`, `chairman_id`);

ALTER TABLE `WORK` ADD FOREIGN KEY (`dept_id`) REFERENCES `DEPARTMENT` (`id`);

ALTER TABLE `WORK` ADD FOREIGN KEY (`lecturer_id`) REFERENCES `LECTURER` (`id`);

ALTER TABLE `COURSE` ADD FOREIGN KEY (`lecturer_id`) REFERENCES `LECTURER` (`id`);

ALTER TABLE `ENROLLMENT` ADD FOREIGN KEY (`co_id`) REFERENCES `COURSE` (`id`);

ALTER TABLE `ENROLLMENT` ADD FOREIGN KEY (`student_id`) REFERENCES `STUDENT` (`id`);

ALTER TABLE `SECTION` ADD FOREIGN KEY (`co_id`) REFERENCES `COURSE` (`id`);

ALTER TABLE `SECTION` ADD FOREIGN KEY (`lecturer_id`) REFERENCES `LECTURER` (`id`);

ALTER TABLE `LECTURE` ADD FOREIGN KEY (`sec_order`, `co_id`) REFERENCES `SECTION` (`sec_order`, `co_id`);

ALTER TABLE `LECTURE` ADD FOREIGN KEY (`lecturer_id`) REFERENCES `LECTURER` (`id`);

ALTER TABLE `LECTURE_MATERIAL_LINK` ADD FOREIGN KEY (`lecture_id`, `sec_order`, `co_id`) REFERENCES `LECTURE` (`id`, `sec_order`, `co_id`);

ALTER TABLE `QUIZ` ADD FOREIGN KEY (`co_id`) REFERENCES `COURSE` (`id`);

ALTER TABLE `QUIZ` ADD FOREIGN KEY (`lecturer_id`) REFERENCES `LECTURER` (`id`);

ALTER TABLE `QUESTION` ADD FOREIGN KEY (`quiz_id`) REFERENCES `QUIZ` (`id`);

ALTER TABLE `QUESTION` ADD FOREIGN KEY (`lecturer_id`) REFERENCES `LECTURER` (`id`);

ALTER TABLE `ATTEMPT` ADD FOREIGN KEY (`student_id`) REFERENCES `STUDENT` (`id`);

ALTER TABLE `ATTEMPT` ADD FOREIGN KEY (`quiz_id`) REFERENCES `QUIZ` (`id`);

ALTER TABLE `ANSWER` ADD FOREIGN KEY (`att_order`, `student_id`, `quiz_id`) REFERENCES `ATTEMPT` (`order`, `student_id`, `quiz_id`);

ALTER TABLE `ANSWER` ADD FOREIGN KEY (`question_id`, `quiz_id`) REFERENCES `QUESTION` (`id`, `quiz_id`);

ALTER TABLE `INTERACT` ADD FOREIGN KEY (`student_id`) REFERENCES `STUDENT` (`id`);

ALTER TABLE `INTERACT` ADD FOREIGN KEY (`lecture_id`, `sec_order`, `co_id`) REFERENCES `LECTURE` (`id`, `sec_order`, `co_id`);
