#!/bin/sh
local_branch_name=$(git symbolic-ref --short HEAD)

# Cho phép commit ở main, nhưng các branch khác phải check regex
if [ "$local_branch_name" != "main" ] && [ "$local_branch_name" != "master" ]; then
    valid_branch_regex="^(feature|fix|hotfix|docs)\/[a-z0-9._-]+$"
    if [[ ! $local_branch_name =~ $valid_branch_regex ]]; then
        echo "❌ Lỗi: Tên branch '$local_branch_name' không đúng chuẩn!"
        exit 1
    fi
fi

npx lint-staged